title:            Markdown Edit
tagline:          A full-featured Markdown Editor For Windows
description:      A full-featured Markdown Editor for Windows with an emphasis on content and keyboard shortcuts
canonical:        https://mike-ward.net/Markdown-Edit
url:              https://mike-ward.net/Markdown-Edit
download:         https://github.com/mike-ward/Markdown-Edit/releases/download/v1.29.1/MarkdownEditSetup.msi
portable:         https://github.com/mike-ward/Markdown-Edit/releases/download/v1.29.1/MarkdownEdit.zip

# Owner/author information
owner:
  name:           Mike Ward
  avatar:         avatar.png
  bio:            Programmer and Bourbon Drinker
  email:          mike@mike-ward.net
  twitter:        mikeward_aa
  github:         mike-ward
  instagram:      
  dribbble:       
  disqus:         mikeward_aa
  location:       "Ann Arbor, MI  USA"
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: "<img src='https://img.shields.io/github/release/mike-ward/markdown-edit.svg?style=flat-square' style='vertical-align:middle;margin-top:-2px;' alt='' />&nbsp;&nbsp;Download"
    url: https://github.com/mike-ward/Markdown-Edit/releases/download/v1.29.1/MarkdownEditSetup.msi
    external: true
  - title: Features
    url: /features
  - title: Blog
    url: /blog
  - title: About
    url: /about
  - title: Forum
    url: https://muut.com/markdown-edit
    external: true
  - title: Github
    url: https://github.com/mike-ward/Markdown-Edit/
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Detroit
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]

gems:
  - jekyll-seo-tag